# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fn0ilmis01_waNcCrhwvYQZ7klbZGXe
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir ("/content/drive/My Drive/Modern AI Project")

import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/Modern AI Project/tv_shows.xlsx')

df.head()

df.drop(columns=['Type'], inplace=True)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Visualize distribution of IMDb ratings
plt.figure(figsize=(10, 6))
sns.histplot(df['IMDb'], bins=20, kde=True, color='skyblue')
plt.title('Distribution of IMDb Ratings')
plt.xlabel('IMDb Rating')
plt.ylabel('Frequency')
plt.show()

# Visualize distribution of Rotten Tomatoes ratings
plt.figure(figsize=(10, 6))
sns.histplot(df['Rotten Tomatoes'], bins=20, kde=True, color='salmon')
plt.title('Distribution of Rotten Tomatoes Ratings')
plt.xlabel('Rotten Tomatoes Rating')
plt.ylabel('Frequency')
plt.show()

# Visualize the number of titles available on each platform
platform_counts = df[['Netflix', 'Prime Video']].sum()
plt.figure(figsize=(8, 6))
platform_counts.plot(kind='bar', color=['red', 'blue'])
plt.title('Number of Titles Available on Netflix and Prime Video')
plt.xlabel('Platform')
plt.ylabel('Number of Titles')
plt.xticks(rotation=0)
plt.show()
